# Generated by Django 3.2.8 on 2021-11-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20211015_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='This indicates if the user is an isntructor or not'),
        ),
    ]
